import React from "react";
import { MapPin, Navigation, Gauge, Sparkles } from "lucide-react";

type TripSummaryProps = {
  costINR: { min: number; max: number };
  places: number;
  distanceKm: number;
  difficulty: string;
};

const USD_RATE = 83;

export default function MobileTripSummary({
  costINR,
  places,
  distanceKm,
  difficulty,
}: TripSummaryProps) {
  const minUSD = Math.round(costINR.min / USD_RATE);
  const maxUSD = Math.round(costINR.max / USD_RATE);

  return (
    <div className="flex flex-col gap-2">
      {/* Gemini AI Badge */}
      <div className="flex items-center gap-1.5 w-fit">
        <Sparkles className="w-3.5 h-3.5 text-orange-300" />
        <span className="text-[10px] font-bold uppercase tracking-wider text-orange-200">
          Generated by Gemini AI
        </span>
      </div>

      <div className="flex flex-wrap items-center gap-x-3 gap-y-2 text-[12px] font-medium text-white/90">
        <div className="flex items-center gap-1.5">
          <span className="font-bold text-white">
            ${minUSD}–${maxUSD}
          </span>
        </div>

        <span className="text-white/40">•</span>

        <div className="flex items-center gap-1.5">
          <MapPin className="w-3.5 h-3.5 text-white/70" />
          <span>{places} places</span>
        </div>

        <span className="text-white/40">•</span>

        <div className="flex items-center gap-1.5">
          <Navigation className="w-3.5 h-3.5 text-white/70" />
          <span>{distanceKm} km</span>
        </div>

        <span className="text-white/40">•</span>

        <div className="flex items-center gap-1.5">
          <Gauge className="w-3.5 h-3.5 text-white/70" />
          <span className="text-white">{difficulty}</span>
        </div>
      </div>
    </div>
  );
}
