export const cambodiaData = {
  slug: 'cambodia',
  destination: 'Cambodia',
  heroImage: 'https://images.pexels.com/photos/5278961/pexels-photo-5278961.jpeg',
  itinerary: {
    destination: 'Cambodia',
    heroImage: 'https://images.pexels.com/photos/5278961/pexels-photo-5278961.jpeg',
    estimatedTotalExpense: '$40–$75',
    estimatedCostINR: { min: 3500, max: 6500 },
    placesCount: 5,
    totalDistanceKm: 25,
    difficulty: 'Moderate',
    bestTimeToVisit: 'November to February (cool, dry season)',
    localCurrency: 'US Dollar widely accepted; Cambodian Riel (KHR 4,100 ≈ $1)',
    language: 'Khmer',
    travelTips: [
      'Buy the 1-day Angkor pass ($37) at the official ticket office only — beware unofficial sellers',
      'Hire a tuk-tuk driver for the entire day ($15–$20) — it\'s the standard way to temple-hop',
      'Dress modestly (cover shoulders and knees) for all temples — you will be turned away',
      'Carry cash — card acceptance is rare outside upscale restaurants',
      'Sunrise at Angkor Wat is crowded; the sunset at Pre Rup or the floating village is equally magical',
    ],
    suggestedStays: [
      { name: 'Mad Monkey Hostel', type: 'Hostel', priceRange: '$8–$15', neighborhood: 'Pub Street Area' },
      { name: 'Viroth\'s Hotel', type: 'Boutique', priceRange: '$90–$140', neighborhood: 'Wat Bo, Siem Reap' },
      { name: 'Shinta Mani Angkor', type: 'Hotel', priceRange: '$200–$350', neighborhood: 'Royal Gardens, Siem Reap' },
    ],
    days: [
      {
        day: 1,
        title: 'Dawn Among the Gods',
        summary: 'Watch sunrise paint Angkor Wat\'s five towers, explore the jungle-consumed Ta Prohm, feast on amok curry, and float through the floating village at sunset.',
        estimatedCost: '$35–$65',
        activities: [
          {
            title: 'Sunrise at Angkor Wat',
            description: 'Arrive at 5 AM to watch the sun rise behind the five lotus-bud towers of the world\'s largest religious monument. As light fills the reflecting pools, the silhouette becomes the image you\'ve seen a thousand times — except now it\'s real.',
            image: null, lat: 13.4125, lng: 103.8670,
            timeOfDay: 'Morning', category: 'LANDMARK', mealType: 'NONE', rating: 4.9,
            aiInsight: 'Angkor Wat faces west (unusual for Hindu temples) — scholars believe it was built as a funerary temple for King Suryavarman II, as west represents death in Hindu cosmology.',
            address: 'Angkor Archaeological Park, Siem Reap',
            duration: '2.5 hours',
            proTip: 'Position yourself at the left (north) reflecting pool — fewer people and better symmetry. After sunrise, enter the temple when crowds disperse around 7:30 AM.',
            travelFromPrevious: null,
          },
          {
            title: 'Ta Prohm — Tomb Raider Temple',
            description: 'The temple that nature reclaimed. Massive silk-cotton and strangler fig trees burst through 12th-century walls, their roots cascading over carved apsara dancers. Deliberately left unrestored to show the jungle\'s power.',
            image: null, lat: 13.4351, lng: 103.8890,
            timeOfDay: 'Morning', category: 'LANDMARK', mealType: 'NONE', rating: 4.8,
            aiInsight: 'The French conservators who restored Angkor chose to leave Ta Prohm "as found" — making it the only major temple where you see what ALL of Angkor looked like when rediscovered in 1860.',
            address: 'Angkor Archaeological Park, Siem Reap',
            duration: '1.5 hours',
            proTip: 'Enter from the east (back) gate — 90% of tourists enter from the west. You\'ll have the iconic tree-root doorway almost to yourself.',
            travelFromPrevious: { mode: 'taxi', duration: '15 mins', distance: '5 km' },
          },
          {
            title: 'Mahob Khmer Restaurant',
            description: 'Elevated Khmer cuisine in a traditional wooden house. The fish amok (coconut curry steamed in banana leaf) and lok lak (stir-fried beef with Kampot pepper) are definitive versions of Cambodia\'s national dishes.',
            image: null, lat: 13.3565, lng: 103.8580,
            timeOfDay: 'Lunchtime', category: 'RESTAURANT', mealType: 'LUNCH', cuisine: 'Khmer', rating: 4.6,
            aiInsight: 'Mahob sources its Kampot pepper directly from pepper farms in the south — this pepper was once the world\'s most prized spice, traded by the ton to French colonial kitchens.',
            address: 'Sivatha Blvd, Krong Siem Reap',
            duration: '1 hour',
            proTip: 'Order the "Khmer tasting menu" for a curated journey through 5 courses. The morning glory stir-fry is a sleeper hit.',
            travelFromPrevious: { mode: 'taxi', duration: '20 mins', distance: '8 km' },
          },
          {
            title: 'Bayon Temple — Angkor Thom',
            description: 'Navigate the labyrinthine corridors of Bayon, where 216 giant stone faces gaze serenely from 54 towers. The bas-reliefs depict everyday Khmer life — markets, fishing, cockfights, childbirth.',
            image: null, lat: 13.4412, lng: 103.8586,
            timeOfDay: 'Afternoon', category: 'LANDMARK', mealType: 'NONE', rating: 4.8,
            aiInsight: 'The faces are believed to depict King Jayavarman VII merged with the bodhisattva Avalokiteshvara. He placed his face on every tower so his gaze would protect all four cardinal directions.',
            address: 'Angkor Thom, Angkor Archaeological Park',
            duration: '1.5 hours',
            proTip: 'Climb to the upper terrace and find a face at eye level — the serene "Mona Lisa of Southeast Asia" smile is best appreciated up close. Afternoon light is warmer for photos.',
            travelFromPrevious: { mode: 'taxi', duration: '10 mins', distance: '4 km' },
          },
          {
            title: 'Kompong Phluk Floating Village',
            description: 'Paddle a wooden boat through a village built entirely on 10m stilts over the Tonle Sap floodplain. Glide through a flooded mangrove forest as the sun sets — the light through the canopy is otherworldly.',
            image: null, lat: 13.2800, lng: 103.9600,
            timeOfDay: 'Evening', category: 'ACTIVITY', mealType: 'NONE', rating: 4.5,
            aiInsight: 'Tonle Sap is the world\'s most productive freshwater fishery — it reverses flow direction twice yearly, creating a unique ecosystem where the lake expands 5x during monsoon season.',
            address: 'Kompong Phluk, Siem Reap Province',
            duration: '2 hours',
            proTip: 'Go between 4–6 PM for golden light. Kompong Phluk is less touristy than Chong Kneas. Tip your boat driver $3–5; it\'s meaningful here.',
            travelFromPrevious: { mode: 'taxi', duration: '35 mins', distance: '20 km' },
          },
        ],
      },
    ],
  },
};
