export const greatWallData = {
  slug: 'great-wall-of-china',
  destination: 'Great Wall of China',
  heroImage: 'https://images.pexels.com/photos/17615499/pexels-photo-17615499.jpeg',
  itinerary: {
    destination: 'Great Wall of China',
    heroImage: 'https://images.pexels.com/photos/17615499/pexels-photo-17615499.jpeg',
    estimatedTotalExpense: '$60–$100',
    estimatedCostINR: { min: 5000, max: 8500 },
    placesCount: 5,
    totalDistanceKm: 130,
    difficulty: 'Moderate',
    bestTimeToVisit: 'April to May, September to November',
    localCurrency: 'Chinese Yuan (¥7.2 ≈ $1)',
    language: 'Mandarin Chinese',
    travelTips: [
      'Download WeChat Pay before arriving — cash is nearly extinct in urban China',
      'A VPN is essential for Google, WhatsApp, and Instagram access',
      'Mutianyu is far less crowded than Badaling — worth the extra drive',
      'Wear proper hiking shoes, not sneakers — the wall steps are steep and uneven',
      'Bring water and snacks — there are no vendors on the wall itself',
    ],
    suggestedStays: [
      { name: 'The Brickyard Retreat', type: 'Boutique', priceRange: '¥600–¥900', neighborhood: 'Mutianyu Village' },
      { name: 'Beijing Downtown Backpackers', type: 'Hostel', priceRange: '¥150–¥250', neighborhood: 'Nanluoguxiang' },
      { name: 'Aman at Summer Palace', type: 'Resort', priceRange: '¥5,000+', neighborhood: 'Haidian District' },
    ],
    days: [
      {
        day: 1,
        title: 'Walking on History\'s Spine',
        summary: 'Ride a cable car to the Mutianyu section, hike the wild wall with mountain panoramas, feast on Beijing duck, and end at the Drum Tower at twilight.',
        estimatedCost: '$50–$90',
        activities: [
          {
            title: 'Mutianyu Great Wall',
            description: 'The best-restored yet uncrowded section of the Wall. Take the cable car up, then walk the battlements from Tower 14 to Tower 23 — the views of mountains draped in mist are staggering.',
            image: null, lat: 40.4319, lng: 116.5704,
            timeOfDay: 'Morning', category: 'LANDMARK', mealType: 'NONE', rating: 4.9,
            aiInsight: 'Mutianyu has 23 watchtowers in just 2.5km — the densest concentration on the entire Wall — because it guarded the critical Jiankou pass into Beijing.',
            address: 'Mutianyu Village, Huairou District, Beijing',
            duration: '3 hours',
            proTip: 'Walk east toward Jiankou (wild/unrestored section) for 20 mins — you\'ll be completely alone with crumbling original wall. Take the toboggan ride down.',
            travelFromPrevious: null,
          },
          {
            title: 'Xinshuangquan Restaurant',
            description: 'A family-run farmhouse restaurant at the Wall\'s base serving hongshao rou (red-braised pork), stir-fried mountain vegetables, and fresh rainbow trout from local streams.',
            image: null, lat: 40.4310, lng: 116.5650,
            timeOfDay: 'Lunchtime', category: 'RESTAURANT', mealType: 'LUNCH', cuisine: 'Chinese Farmhouse', rating: 4.3,
            aiInsight: 'The village\'s trout farms use cold mountain spring water — the same water source that supplied the Ming Dynasty garrison above.',
            address: 'Mutianyu Village, Huairou, Beijing',
            duration: '1 hour',
            proTip: 'Order the "nongjiafan" (farmer\'s feast) set menu — 6 dishes for ¥150, enough for 2–3 people.',
            travelFromPrevious: { mode: 'walk', duration: '10 mins', distance: '1 km' },
          },
          {
            title: 'Nanluoguxiang Hutong',
            description: 'Back in Beijing, explore this 800-year-old hutong (alley neighborhood). Duck into courtyard homes, browse indie boutiques, and try tanghulu (candied hawthorn) and jianbing (savory crepe).',
            image: null, lat: 39.9372, lng: 116.4033,
            timeOfDay: 'Afternoon', category: 'LANDMARK', mealType: 'NONE', rating: 4.4,
            aiInsight: 'This hutong was part of the original Yuan Dynasty (1271) city grid — the courtyard houses follow the same layout Kublai Khan\'s planners designed.',
            address: 'Nanluoguxiang, Dongcheng District, Beijing',
            duration: '1.5 hours',
            proTip: 'Turn off the main drag into the branching side hutongs (Mao\'er, Qinlao) for authentic residential life.',
            travelFromPrevious: { mode: 'taxi', duration: '90 mins', distance: '75 km' },
          },
          {
            title: 'Peking Duck at Da Dong',
            description: 'Beijing\'s most acclaimed duck restaurant. The "Super-Lean" roast duck has 65% less fat than traditional versions — impossibly crispy skin with melt-in-mouth meat, carved tableside.',
            image: null, lat: 39.9154, lng: 116.4607,
            timeOfDay: 'Evening', category: 'RESTAURANT', mealType: 'DINNER', cuisine: 'Peking Duck', rating: 4.7,
            aiInsight: 'Da Dong\'s chef Dong Zhenxiang spent 30 years perfecting his fruit-wood roasting technique — each duck is roasted at a precise 280°C for exactly 65 minutes.',
            address: 'Jinbao Place, 88 Jinbao St, Dongcheng, Beijing',
            duration: '1.5 hours',
            proTip: 'Order the duck with the "thin pancake" wrapping and sugar dip — an imperial-style preparation most tourists miss. Reserve 2 days ahead.',
            travelFromPrevious: { mode: 'taxi', duration: '20 mins', distance: '8 km' },
          },
          {
            title: 'Drum & Bell Towers at Twilight',
            description: 'Climb the 67-step staircase of the 600-year-old Drum Tower for panoramic views over Beijing\'s hutong rooftops at golden hour. The Bell Tower across the square dates to 1420.',
            image: null, lat: 39.9417, lng: 116.3867,
            timeOfDay: 'Evening', category: 'LANDMARK', mealType: 'NONE', rating: 4.5,
            aiInsight: 'These towers told time for all of Beijing for 500 years — 24 drums were struck at precise intervals. The largest drum\'s original cowhide skin is 600 years old.',
            address: 'Zhonglou, Dongcheng District, Beijing',
            duration: '45 mins',
            proTip: 'Go at 5 PM for the traditional drumming performance (included with entry). The bell tower view is less crowded.',
            travelFromPrevious: { mode: 'taxi', duration: '15 mins', distance: '5 km' },
          },
        ],
      },
    ],
  },
};
