export const japanData = {
  slug: 'japan',
  destination: 'Japan',
  heroImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=2000&auto=format&fit=crop',
  itinerary: {
    destination: 'Japan',
    heroImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=2000&auto=format&fit=crop',
    estimatedTotalExpense: '$80–$130',
    estimatedCostINR: { min: 6500, max: 11000 },
    placesCount: 6,
    totalDistanceKm: 22,
    difficulty: 'Easy',
    bestTimeToVisit: 'March to May (cherry blossom), October to November (autumn)',
    localCurrency: 'Japanese Yen (¥150 ≈ $1)',
    language: 'Japanese',
    travelTips: [
      'Get a Suica/Pasmo IC card for all transit — tap on, tap off, works everywhere',
      'Bow when greeting — a slight nod is fine for tourists',
      'Cash is still king in small restaurants and shrines — carry ¥10,000+ daily',
      'Never tip anywhere — it can be considered rude',
      'Convenience stores (7-Eleven, Lawson) have excellent food — onigiri and egg sandwiches are elite',
    ],
    suggestedStays: [
      { name: 'Nui. Hostel & Bar Lounge', type: 'Hostel', priceRange: '¥4,000–¥6,000', neighborhood: 'Kuramae, Asakusa' },
      { name: 'Hotel Gracery Shinjuku', type: 'Hotel', priceRange: '¥12,000–¥18,000', neighborhood: 'Kabukicho, Shinjuku' },
      { name: 'Aman Tokyo', type: 'Hotel', priceRange: '¥80,000+', neighborhood: 'Otemachi, Marunouchi' },
    ],
    days: [
      {
        day: 1,
        title: 'Shrines, Street Food & Shibuya Lights',
        summary: 'Find serenity at Meiji Shrine\'s forest, devour the world\'s best ramen, cross the planet\'s busiest intersection, and end in the neon-drenched alleys of Golden Gai.',
        estimatedCost: '$70–$120',
        activities: [
          {
            title: 'Meiji Jingu Shrine',
            description: 'Walk through a towering torii gate into 170 acres of old-growth forest in central Tokyo. Meiji Shrine honors Emperor Meiji and feels impossibly tranquil for a city of 14 million.',
            image: null, lat: 35.6764, lng: 139.6993,
            timeOfDay: 'Morning', category: 'LANDMARK', mealType: 'NONE', rating: 4.8,
            aiInsight: 'The 100,000 trees in this forest were donated from every prefecture in Japan and planted by 100,000 volunteers in 1920 — it\'s an entirely human-made "natural" forest.',
            address: '1-1 Yoyogikamizonocho, Shibuya, Tokyo 151-8557',
            duration: '1.5 hours',
            proTip: 'Arrive before 9 AM. Write a wish on an ema (wooden plaque) — ¥500 at the shrine office.',
            travelFromPrevious: null,
          },
          {
            title: 'Takeshita Street & Harajuku',
            description: 'Plunge into Tokyo\'s youth culture epicenter — a narrow pedestrian street exploding with kawaii fashion, crepe stands, and cotton candy the size of your head.',
            image: null, lat: 35.6706, lng: 139.7027,
            timeOfDay: 'Morning', category: 'LANDMARK', mealType: 'NONE', rating: 4.3,
            aiInsight: 'Harajuku\'s street fashion scene literally created entire global fashion movements — Lolita, decora, visual kei all started within a 500m radius of this street.',
            address: 'Takeshita Dori, Jingumae, Shibuya, Tokyo',
            duration: '45 mins',
            proTip: 'Skip the main drag; turn into Cat Street (parallel) for vintage shops and better cafés.',
            travelFromPrevious: { mode: 'walk', duration: '8 mins', distance: '0.6 km' },
          },
          {
            title: 'Fuunji Tsukemen',
            description: 'Tokyo\'s most legendary tsukemen (dipping ramen) — ultra-thick fish-pork broth so intensely flavored it\'s almost a paste. The queue is part of the ritual.',
            image: null, lat: 35.6896, lng: 139.6998,
            timeOfDay: 'Lunchtime', category: 'RESTAURANT', mealType: 'LUNCH', cuisine: 'Japanese Ramen', rating: 4.7,
            aiInsight: 'Fuunji\'s broth is double-stacked: a 12-hour pork bone base + dried bonito and mackerel — the umami density is off the charts.',
            address: '2-14-3 Yoyogi, Shibuya, Tokyo 151-0053',
            duration: '45 mins',
            proTip: 'Order "tokumori" (large noodles) for only ¥100 extra. Ask for "atsu-mori" (hot noodles) for better dipping.',
            travelFromPrevious: { mode: 'train', duration: '10 mins', distance: '2 km' },
          },
          {
            title: 'Shibuya Crossing & Shibuya Sky',
            description: 'Stand at the world\'s busiest pedestrian crossing (3,000 people per signal change), then ride to Shibuya Sky\'s 230m open-air rooftop for a jaw-dropping 360° view of Tokyo stretching to Mt. Fuji.',
            image: null, lat: 35.6595, lng: 139.7004,
            timeOfDay: 'Afternoon', category: 'LANDMARK', mealType: 'NONE', rating: 4.6,
            aiInsight: 'Shibuya Crossing wasn\'t designed to be famous — it\'s a standard "scramble" intersection. Its fame came from the movie Lost in Translation (2003) and went viral from there.',
            address: '2-24-12 Shibuya, Shibuya-ku, Tokyo 150-6145',
            duration: '1.5 hours',
            proTip: 'Book Shibuya Sky for 30 mins before sunset — you\'ll get daylight AND night views in one visit.',
            travelFromPrevious: { mode: 'train', duration: '5 mins', distance: '2 km' },
          },
          {
            title: 'Omoide Yokocho Yakitori Dinner',
            description: 'Squeeze into a 6-seat counter in this post-WWII alley of tiny yakitori bars. Smoke rises from charcoal grills as chefs brush tare sauce on every skewer. Gritty, authentic, unforgettable.',
            image: null, lat: 35.6938, lng: 139.6989,
            timeOfDay: 'Evening', category: 'RESTAURANT', mealType: 'DINNER', cuisine: 'Japanese Yakitori', rating: 4.5,
            aiInsight: 'These alleys survived Tokyo\'s 1999 fire and constant redevelopment threats — they\'re the last physical remnant of post-war black market Tokyo.',
            address: '1 Chome Nishishinjuku, Shinjuku, Tokyo 160-0023',
            duration: '1 hour',
            proTip: 'Order "negima" (chicken thigh with leek) and "tsukune" (chicken meatball) — the two essential skewers. Pair with a cold Asahi draft.',
            travelFromPrevious: { mode: 'train', duration: '8 mins', distance: '4 km' },
          },
          {
            title: 'Golden Gai Bar Crawl',
            description: 'Navigate six narrow alleys packed with 200+ bars, each seating 6–10 people. Every bar has a theme — vinyl records, horror movies, jazz, philosophy. Pick 2–3 and let the night unfold.',
            image: null, lat: 35.6942, lng: 139.7038,
            timeOfDay: 'Evening', category: 'ACTIVITY', mealType: 'NONE', rating: 4.7,
            aiInsight: 'Golden Gai bars have a "cover charge" culture (¥500–1500) — it\'s not a tourist trap, it\'s how 6-seat bars survive. Think of it as a membership to a secret club.',
            address: 'Golden Gai, Kabukicho 1 Chome, Shinjuku, Tokyo',
            duration: '1.5 hours',
            proTip: 'Look for bars with English menus in the window. "Bar Albatross" is the classic first-timer pick with its gorgeous stained-glass interior.',
            travelFromPrevious: { mode: 'walk', duration: '5 mins', distance: '0.4 km' },
          },
        ],
      },
    ],
  },
};
