export const maldivesData = {
  slug: 'maldives',
  destination: 'Maldives',
  heroImage: 'https://images.pexels.com/photos/29289155/pexels-photo-29289155.jpeg',
  itinerary: {
    destination: 'Maldives',
    heroImage: 'https://images.pexels.com/photos/29289155/pexels-photo-29289155.jpeg',
    estimatedTotalExpense: '$120–$180',
    estimatedCostINR: { min: 10000, max: 15000 },
    placesCount: 5,
    totalDistanceKm: 8,
    difficulty: 'Easy',
    bestTimeToVisit: 'November to April (dry season)',
    localCurrency: 'Maldivian Rufiyaa (MVR 15.4 ≈ $1)',
    language: 'Dhivehi (English widely spoken)',
    travelTips: [
      'Most resorts are on private islands — arrange speedboat/seaplane transfers in advance',
      'Respect local customs: cover up when visiting inhabited islands (not resort islands)',
      'Carry reef-safe sunscreen — coral bleaching is a real concern',
      'Friday is the local weekend; some shops on local islands close',
      'Tap water is desalinated — stick to bottled water on local islands',
    ],
    suggestedStays: [
      { name: 'Cinnamon Dhonveli', type: 'Resort', priceRange: '$200–$350', neighborhood: 'North Malé Atoll' },
      { name: 'Arena Beach Hotel', type: 'Hotel', priceRange: '$80–$130', neighborhood: 'Maafushi Island' },
      { name: 'Kaani Grand Seaview', type: 'Boutique', priceRange: '$100–$180', neighborhood: 'Maafushi Island' },
    ],
    days: [
      {
        day: 1,
        title: 'Turquoise Waters & Island Soul',
        summary: 'Dive into the Maldives with a morning snorkel on a pristine house reef, feast on Maldivian curry, explore a local island\'s culture, and close with a sunset dolphin cruise.',
        estimatedCost: '$100–$160',
        activities: [
          {
            title: 'Snorkeling at Banana Reef',
            description: 'One of the Maldives\' first dive sites, Banana Reef is a curved reef wall teeming with moray eels, Napoleon wrasses, and vibrant soft corals. Snorkel the shallow ledge for world-class underwater scenery.',
            image: null,
            lat: 4.2658,
            lng: 73.5322,
            timeOfDay: 'Morning',
            category: 'ACTIVITY',
            mealType: 'NONE',
            rating: 4.8,
            aiInsight: 'The reef\'s banana-shaped curve creates a natural current that brings pelagic fish unusually close — you\'ll see species here that divers chase at deeper sites.',
            address: 'Banana Reef, North Malé Atoll, Maldives',
            duration: '2 hours',
            proTip: 'Go before 9 AM when visibility peaks at 30m+ and boats haven\'t stirred the sand.',
            travelFromPrevious: null,
          },
          {
            title: 'The Falhu Restaurant',
            description: 'A family-run eatery on Maafushi serving authentic Maldivian mas huni (tuna & coconut), garudhiya fish broth, and roshi flatbread. The flavors are simple but deeply satisfying.',
            image: null,
            lat: 3.9431,
            lng: 73.5257,
            timeOfDay: 'Lunchtime',
            category: 'RESTAURANT',
            mealType: 'LUNCH',
            cuisine: 'Maldivian',
            rating: 4.5,
            aiInsight: 'This is what locals actually eat — skip the resort buffets and taste real island cooking with hand-ground coconut and line-caught tuna.',
            address: 'Maafushi Island Main Road, Maafushi, Maldives',
            duration: '1 hour',
            proTip: 'Order the "hedhikaa" short-eats platter — bajiya (samosa-style snacks) and gulha are addictive.',
            travelFromPrevious: { mode: 'ferry', duration: '35 mins', distance: '6 km' },
          },
          {
            title: 'Maafushi Island Walk',
            description: 'Stroll through one of the Maldives\' most popular local islands. Visit the pastel-painted mosques, tiny souvenir shops, and the bikini beach — the only public beach where tourists can swim freely.',
            image: null,
            lat: 3.9400,
            lng: 73.5230,
            timeOfDay: 'Afternoon',
            category: 'LANDMARK',
            mealType: 'NONE',
            rating: 4.3,
            aiInsight: 'Maafushi transformed from a quiet fishing village to the Maldives\' budget-travel hub in under a decade — it\'s the perfect window into how island life and tourism coexist.',
            address: 'Maafushi Village, Kaafu Atoll, Maldives',
            duration: '1.5 hours',
            proTip: 'Walk to the island\'s south tip for an empty sandbank that appears at low tide.',
            travelFromPrevious: { mode: 'walk', duration: '5 mins', distance: '0.3 km' },
          },
          {
            title: 'Sandbank Excursion',
            description: 'Take a dhoni (traditional boat) to a tiny sandbank rising from the turquoise lagoon. Nothing around but crystal water and white sand — pure Maldives postcard.',
            image: null,
            lat: 3.9200,
            lng: 73.5100,
            timeOfDay: 'Afternoon',
            category: 'ACTIVITY',
            mealType: 'NONE',
            rating: 4.7,
            aiInsight: 'These sandbanks shift with the tides and seasons; the one near Maafushi is semi-permanent and has the best surrounding reef for spontaneous snorkeling.',
            address: 'Sandbank near Maafushi, Kaafu Atoll',
            duration: '1.5 hours',
            proTip: 'Bring your own snorkel gear — boat operators charge double for rental.',
            travelFromPrevious: { mode: 'ferry', duration: '15 mins', distance: '2 km' },
          },
          {
            title: 'Sunset Dolphin Cruise',
            description: 'Board a traditional dhoni for a sunset cruise through the atoll. Spinner dolphins are spotted on 95% of trips — watching them leap against a molten-orange sky is the Maldives\' most iconic experience.',
            image: null,
            lat: 3.9550,
            lng: 73.4900,
            timeOfDay: 'Evening',
            category: 'ACTIVITY',
            mealType: 'NONE',
            rating: 4.9,
            aiInsight: 'The channel between Maafushi and Gulhi is a dolphin highway — pods of 50–100 spinners use it daily, making this one of the world\'s most reliable wild dolphin encounters.',
            address: 'Maafushi Harbor Departure, Kaafu Atoll',
            duration: '1.5 hours',
            proTip: 'Sit at the bow, not the stern — dolphins ride the boat\'s pressure wave and come within arm\'s reach.',
            travelFromPrevious: { mode: 'walk', duration: '10 mins', distance: '0.5 km' },
          },
        ],
      },
    ],
  },
};
