export const romeData = {
  slug: 'rome',
  destination: 'Rome',
  heroImage: 'https://images.pexels.com/photos/1797161/pexels-photo-1797161.jpeg',
  itinerary: {
    destination: 'Rome',
    heroImage: 'https://images.pexels.com/photos/1797161/pexels-photo-1797161.jpeg',
    estimatedTotalExpense: '$100–$160',
    estimatedCostINR: { min: 8500, max: 13500 },
    placesCount: 6,
    totalDistanceKm: 7,
    difficulty: 'Easy',
    bestTimeToVisit: 'April to June, September to October',
    localCurrency: 'Euro (€1 ≈ $1.08)',
    language: 'Italian',
    travelTips: [
      'Wear covered shoulders and knees for churches — you will be turned away otherwise',
      'Drink from the "nasoni" cast-iron street fountains — the water is fresh and safe',
      'Always validate your metro/bus ticket or face a €50 fine from inspectors',
      'Book the Colosseum at least 2 weeks in advance — same-day tickets sell out',
      'Avoid restaurants with picture menus near tourist sites — they\'re overpriced and mediocre',
    ],
    suggestedStays: [
      { name: 'The Yellow Hostel', type: 'Hostel', priceRange: '€30–€55', neighborhood: 'Termini' },
      { name: 'Hotel Lancelot', type: 'Hotel', priceRange: '€100–€160', neighborhood: 'Monti / Colosseum' },
      { name: 'Hotel de Russie', type: 'Hotel', priceRange: '€350–€500', neighborhood: 'Piazza del Popolo' },
    ],
    days: [
      {
        day: 1,
        title: 'Gladiators, Gelato & Golden Hour',
        summary: 'Walk through the Colosseum\'s arena floor, toss a coin at Trevi, feast on cacio e pepe in Trastevere, and watch sunset from the Pincian Hill.',
        estimatedCost: '$80–$140',
        activities: [
          {
            title: 'Colosseum & Roman Forum',
            description: 'Enter the 2,000-year-old arena where gladiators fought, then walk through the Forum\'s ruins — the political heart of Western civilization for 1,000 years.',
            image: null, lat: 41.8902, lng: 12.4922,
            timeOfDay: 'Morning', category: 'LANDMARK', mealType: 'NONE', rating: 4.8,
            aiInsight: 'The underground hypogeum (animal cages & lifts) only reopened in 2021 after a €18M restoration — you\'re seeing tunnels hidden for centuries.',
            address: 'Piazza del Colosseo, 1, 00184 Roma',
            duration: '2.5 hours',
            proTip: 'Book the "Full Experience" ticket for Forum + Palatine Hill — it\'s valid 2 days.',
            travelFromPrevious: null,
          },
          {
            title: 'Roscioli Salumeria',
            description: 'A legendary deli-restaurant where you eat cacio e pepe surrounded by wheels of aged Pecorino and hanging prosciutto. The carbonara is equally transcendent.',
            image: null, lat: 41.8937, lng: 12.4726,
            timeOfDay: 'Lunchtime', category: 'RESTAURANT', mealType: 'LUNCH', cuisine: 'Italian', rating: 4.7,
            aiInsight: 'Roscioli sources its guanciale from a single family farm in Amatrice — the same village that invented the dish.',
            address: 'Via dei Giubbonari, 21, 00186 Roma',
            duration: '1 hour',
            proTip: 'Skip the menu — ask the waiter "cosa mi consigli?" (what do you recommend) for off-menu specials.',
            travelFromPrevious: { mode: 'walk', duration: '25 mins', distance: '2 km' },
          },
          {
            title: 'Trevi Fountain & Pantheon',
            description: 'Toss a coin over your left shoulder at the Baroque Trevi, then walk 5 minutes to the Pantheon — its 2,000-year-old unreinforced concrete dome is still the world\'s largest.',
            image: null, lat: 41.9009, lng: 12.4833,
            timeOfDay: 'Afternoon', category: 'LANDMARK', mealType: 'NONE', rating: 4.6,
            aiInsight: 'The Pantheon\'s oculus (9m hole in the dome) is open to rain — the floor has 22 nearly invisible drainage holes that Romans engineered in 125 AD.',
            address: 'Piazza di Trevi, 00187 Roma',
            duration: '1 hour',
            proTip: 'Visit Trevi at 7:30 AM or after 9 PM to see it without crowds.',
            travelFromPrevious: { mode: 'walk', duration: '15 mins', distance: '1.2 km' },
          },
          {
            title: 'Trastevere Neighborhood',
            description: 'Cross the Tiber into Rome\'s most charming neighborhood — ivy-draped ochre buildings, busking musicians, artisan workshops, and the golden mosaics of Santa Maria basilica.',
            image: null, lat: 41.8867, lng: 12.4700,
            timeOfDay: 'Afternoon', category: 'LANDMARK', mealType: 'NONE', rating: 4.5,
            aiInsight: 'Trastevere was historically Rome\'s immigrant quarter — its name literally means "across the Tiber" — which gave it the eclectic, bohemian character it still has today.',
            address: 'Piazza di Santa Maria in Trastevere, Roma',
            duration: '1.5 hours',
            proTip: 'Walk Via della Lungaretta for the best street art and smallest artisan leather shops.',
            travelFromPrevious: { mode: 'bus', duration: '12 mins', distance: '2 km' },
          },
          {
            title: 'Dinner at Da Enzo al 29',
            description: 'The most beloved trattoria in Trastevere. No reservations, paper tablecloths, and the best cacio e pepe and fried artichokes (carciofi alla giudia) in the city.',
            image: null, lat: 41.8856, lng: 12.4713,
            timeOfDay: 'Evening', category: 'RESTAURANT', mealType: 'DINNER', cuisine: 'Roman', rating: 4.7,
            aiInsight: 'Da Enzo uses only Pecorino Romano DOP aged 8 months — most restaurants use 5-month cheese, which is why their cacio e pepe tastes different.',
            address: 'Via dei Vascellari, 29, 00153 Roma',
            duration: '1 hour',
            proTip: 'Arrive at 7 PM (opening) to beat the queue. Share a tiramisù — it\'s enormous.',
            travelFromPrevious: { mode: 'walk', duration: '5 mins', distance: '0.3 km' },
          },
          {
            title: 'Sunset at Pincian Hill',
            description: 'Watch the Roman skyline turn gold from the Pincian Hill terrace above Piazza del Popolo. St. Peter\'s dome dominates the horizon. Free.',
            image: null, lat: 41.9113, lng: 12.4823,
            timeOfDay: 'Evening', category: 'LANDMARK', mealType: 'NONE', rating: 4.8,
            aiInsight: 'This exact viewpoint was painted by Corot, Turner, and dozens of Grand Tour artists — the sunset alignment with St. Peter\'s is identical to paintings from 1820.',
            address: 'Terrazza del Pincio, Viale Gabriele d\'Annunzio, Roma',
            duration: '45 mins',
            proTip: 'Grab a gelato from "Venchi" at the base of the Spanish Steps on your walk up.',
            travelFromPrevious: { mode: 'taxi', duration: '12 mins', distance: '3 km' },
          },
        ],
      },
    ],
  },
};
