export const scotlandData = {
  slug: 'scotland',
  destination: 'Scotland',
  heroImage: 'https://images.unsplash.com/photo-1641038321852-bc96d970e2e5?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  itinerary: {
    destination: 'Scotland',
    heroImage: 'https://images.unsplash.com/photo-1641038321852-bc96d970e2e5?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    estimatedTotalExpense: '$100–$170',
    estimatedCostINR: { min: 8500, max: 14000 },
    placesCount: 5,
    totalDistanceKm: 6,
    difficulty: 'Easy',
    bestTimeToVisit: 'May to September (longest days, mildest weather)',
    localCurrency: 'British Pound (£1 ≈ $1.27)',
    language: 'English, Scots Gaelic',
    travelTips: [
      'Weather changes every hour — the saying is "four seasons in one day." Layer up always',
      'Scottish banknotes are legal tender in England but some shops refuse them — exchange if heading south',
      'Haggis is far better than its reputation suggests — try it at least once',
      'Free public toilets are rare; use ones in pubs or department stores',
      'Edinburgh\'s Old Town is extremely hilly with cobblestones — wear sturdy shoes',
    ],
    suggestedStays: [
      { name: 'Castle Rock Hostel', type: 'Hostel', priceRange: '£25–£40', neighborhood: 'Old Town, Edinburgh' },
      { name: 'The Grassmarket Hotel', type: 'Boutique', priceRange: '£120–£180', neighborhood: 'Grassmarket, Edinburgh' },
      { name: 'The Balmoral', type: 'Hotel', priceRange: '£350–£500', neighborhood: 'Princes Street, Edinburgh' },
    ],
    days: [
      {
        day: 1,
        title: 'Cobblestones, Castles & a Wee Dram',
        summary: 'Explore Edinburgh Castle\'s medieval battlements, descend the Royal Mile through centuries of history, savour a whisky flight in a candlelit vault, and watch sunset paint Arthur\'s Seat golden.',
        estimatedCost: '$90–$150',
        activities: [
          {
            title: 'Edinburgh Castle',
            description: 'Perched atop an extinct volcano, Edinburgh Castle has dominated the skyline for 900 years. See the Stone of Destiny, the One O\'Clock Gun, and panoramic views stretching to the Firth of Forth.',
            image: null, lat: 55.9486, lng: -3.1999,
            timeOfDay: 'Morning', category: 'LANDMARK', mealType: 'NONE', rating: 4.7,
            aiInsight: 'The castle rock is a volcanic plug — the glacier that carved Edinburgh split around it, creating the "crag and tail" formation that became the Royal Mile.',
            address: 'Castlehill, Edinburgh EH1 2NG, Scotland',
            duration: '2 hours',
            proTip: 'Book the 9:30 AM entry online to skip the queue. The Crown Jewels room empties out after 11 AM.',
            travelFromPrevious: null,
          },
          {
            title: 'The Witchery by the Castle',
            description: 'Dine in a gothic-baroque dining room dripping with candlelight and tapestries, steps from the castle gate. The Scottish seafood platter and Angus beef are outstanding.',
            image: null, lat: 55.9490, lng: -3.1960,
            timeOfDay: 'Lunchtime', category: 'RESTAURANT', mealType: 'LUNCH', cuisine: 'Scottish', rating: 4.6,
            aiInsight: 'The building sits on the spot where over 300 women were burned as witches in the 16th–17th centuries — the restaurant\'s name and occult décor are a deliberate homage.',
            address: '352 Castlehill, Royal Mile, Edinburgh EH1 2NF',
            duration: '1 hour',
            proTip: 'Book the Secret Garden room (glass-roofed courtyard) for the most atmospheric lunch in Edinburgh.',
            travelFromPrevious: { mode: 'walk', duration: '2 mins', distance: '0.1 km' },
          },
          {
            title: 'Royal Mile & St Giles\' Cathedral',
            description: 'Walk the medieval Royal Mile from the castle to Holyrood. Pop into St Giles\' Cathedral for its stunning Thistle Chapel, explore the hidden closes (narrow alleyways) branching off the main street.',
            image: null, lat: 55.9494, lng: -3.1905,
            timeOfDay: 'Afternoon', category: 'LANDMARK', mealType: 'NONE', rating: 4.5,
            aiInsight: 'The closes were Edinburgh\'s original vertical city — families stacked 14 stories high in the 1700s, with the wealthy on top and the poor at street level.',
            address: 'High St, Edinburgh EH1 1RE, Scotland',
            duration: '1.5 hours',
            proTip: 'Duck into Advocate\'s Close for the best framed view of the Scott Monument — most tourists walk right past it.',
            travelFromPrevious: { mode: 'walk', duration: '5 mins', distance: '0.4 km' },
          },
          {
            title: 'Scotch Whisky Experience',
            description: 'Take the barrel ride through the distillation process, then taste a curated flight of single malts from each of Scotland\'s five whisky regions. The vault holds the world\'s largest collection of Scotch whisky.',
            image: null, lat: 55.9489, lng: -3.1975,
            timeOfDay: 'Afternoon', category: 'ACTIVITY', mealType: 'NONE', rating: 4.6,
            aiInsight: 'The collection contains 3,384 bottles — every distillery in Scotland is represented. The Diageo Claive Vidiz Collection alone is insured for over £1 million.',
            address: '354 Castlehill, Edinburgh EH1 2NE, Scotland',
            duration: '1 hour',
            proTip: 'Upgrade to the "Morning Masterclass" for a deeper tasting with rare drams not available on the standard tour.',
            travelFromPrevious: { mode: 'walk', duration: '5 mins', distance: '0.3 km' },
          },
          {
            title: 'Sunset at Arthur\'s Seat',
            description: 'Hike the 251m ancient volcano rising from the heart of Edinburgh. The 45-minute ascent rewards you with a 360° panorama of the city, castle, Firth of Forth, and rolling Scottish countryside — magical at sunset.',
            image: null, lat: 55.9441, lng: -3.1618,
            timeOfDay: 'Evening', category: 'LANDMARK', mealType: 'NONE', rating: 4.8,
            aiInsight: 'Arthur\'s Seat is a 350-million-year-old volcano and one of the sites where James Hutton founded modern geology in 1788 — you\'re literally walking on the birthplace of earth science.',
            address: 'Arthur\'s Seat, Holyrood Park, Edinburgh EH8 8AZ',
            duration: '1.5 hours',
            proTip: 'Take the path from Dunsapie Loch (east side) for a gentler, less crowded ascent. Summer sunsets are around 9:30 PM.',
            travelFromPrevious: { mode: 'walk', duration: '25 mins', distance: '2.5 km' },
          },
        ],
      },
    ],
  },
};
