export const singaporeData = {
  slug: 'singapore',
  destination: 'Singapore',
  heroImage: 'https://images.pexels.com/photos/20768105/pexels-photo-20768105.jpeg',
  itinerary: {
    destination: 'Singapore',
    heroImage: 'https://images.pexels.com/photos/20768105/pexels-photo-20768105.jpeg',
    estimatedTotalExpense: '$80–$140',
    estimatedCostINR: { min: 6500, max: 11500 },
    placesCount: 6,
    totalDistanceKm: 18,
    difficulty: 'Easy',
    bestTimeToVisit: 'February to April (driest months)',
    localCurrency: 'Singapore Dollar (SGD 1.34 ≈ $1)',
    language: 'English, Mandarin, Malay, Tamil',
    travelTips: [
      'The MRT is fast, cheap, and covers the entire island — skip taxis for most trips',
      'Hawker centres are the best food in Singapore and cost $3–$6 per dish',
      'Air conditioning is aggressive — carry a light jacket for malls and MRT',
      'Chewing gum is banned for sale (not possession) — don\'t import it',
      'Download the "SimplyGo" app to tap-and-pay on all public transport',
    ],
    suggestedStays: [
      { name: 'Generator Singapore', type: 'Hostel', priceRange: 'SGD 40–70', neighborhood: 'Lavender / Little India' },
      { name: 'Hotel Mono', type: 'Boutique', priceRange: 'SGD 120–180', neighborhood: 'Chinatown' },
      { name: 'Marina Bay Sands', type: 'Resort', priceRange: 'SGD 500–800', neighborhood: 'Marina Bay' },
    ],
    days: [
      {
        day: 1,
        title: 'Hawker Trails & Supertrees',
        summary: 'Start at the world\'s best hawker centre for breakfast, explore the colonial Civic District, wander through Gardens by the Bay\'s cloud forest, and end with the Supertree light show at night.',
        estimatedCost: '$60–$110',
        activities: [
          {
            title: 'Tiong Bahru Market Breakfast',
            description: 'Singapore\'s most stylish hawker centre set in an Art Deco building. Queue for chwee kueh (steamed rice cakes with preserved radish) and kopi from the legendary Ah Chiang stall.',
            image: null, lat: 1.2847, lng: 103.8320,
            timeOfDay: 'Morning', category: 'RESTAURANT', mealType: 'BREAKFAST', cuisine: 'Singaporean', rating: 4.6,
            aiInsight: 'Tiong Bahru was Singapore\'s first public housing estate (1930s) — the neighborhood\'s Art Deco architecture makes it feel more like a European quarter than a tropical city.',
            address: '30 Seng Poh Rd, Singapore 168898',
            duration: '45 mins',
            proTip: 'Stall #02-05 (Jian Bo Shui Kueh) has a permanent queue — join it, it moves fast and the chwee kueh is the city\'s best.',
            travelFromPrevious: null,
          },
          {
            title: 'National Gallery Singapore',
            description: 'Southeast Asia\'s largest art museum housed in the former Supreme Court and City Hall — two stunning colonial buildings connected by a futuristic glass canopy.',
            image: null, lat: 1.2903, lng: 103.8515,
            timeOfDay: 'Morning', category: 'LANDMARK', mealType: 'NONE', rating: 4.7,
            aiInsight: 'The rooftop bar "Smoke & Mirrors" has the best straight-on view of Marina Bay Sands — better than from the Sands itself.',
            address: '1 St Andrew\'s Rd, Singapore 178957',
            duration: '1.5 hours',
            proTip: 'Entry is free for Singapore residents; tourists pay SGD 20 — but the architecture alone is worth it.',
            travelFromPrevious: { mode: 'bus', duration: '15 mins', distance: '3 km' },
          },
          {
            title: 'Maxwell Food Centre — Tian Tian Chicken Rice',
            description: 'The hawker stall that put Singapore chicken rice on the global map. Silky poached chicken over fragrant rice with chili-ginger sauce — Anthony Bourdain\'s favorite.',
            image: null, lat: 1.2804, lng: 103.8448,
            timeOfDay: 'Lunchtime', category: 'RESTAURANT', mealType: 'LUNCH', cuisine: 'Singaporean', rating: 4.7,
            aiInsight: 'Tian Tian\'s chicken is poached in a precisely temperature-controlled bath then ice-shocked — it\'s a technique most restaurants can\'t replicate, giving the skin its signature jelly-like texture.',
            address: '1 Kadayanallur St, Singapore 069184',
            duration: '45 mins',
            proTip: 'Arrive by 11:30 AM — they regularly sell out by 1 PM. Get the "roasted" version for crispier skin.',
            travelFromPrevious: { mode: 'walk', duration: '10 mins', distance: '0.8 km' },
          },
          {
            title: 'Gardens by the Bay — Cloud Forest',
            description: 'Step into a 35m-tall glass dome housing a cloud forest mountain with the world\'s tallest indoor waterfall. The aerial walkway spirals through mist-wrapped orchids and ferns.',
            image: null, lat: 1.2816, lng: 103.8636,
            timeOfDay: 'Afternoon', category: 'LANDMARK', mealType: 'NONE', rating: 4.8,
            aiInsight: 'The Cloud Forest replicates ecosystems found above 2,000m in tropical mountains — species here are among the most climate-threatened on Earth. It\'s conservation disguised as spectacle.',
            address: '18 Marina Gardens Dr, Singapore 018953',
            duration: '2 hours',
            proTip: 'Start from the top (take the elevator) and walk down — the waterfall reveal from above is far more dramatic.',
            travelFromPrevious: { mode: 'walk', duration: '20 mins', distance: '1.8 km' },
          },
          {
            title: 'Lau Pa Sat Satay Street Dinner',
            description: 'After 7 PM, Boon Tat Street beside Lau Pa Sat closes to traffic and fills with smoke from dozens of satay grills. Order mixed chicken-mutton satay with peanut sauce and ketupat rice cakes.',
            image: null, lat: 1.2806, lng: 103.8505,
            timeOfDay: 'Evening', category: 'RESTAURANT', mealType: 'DINNER', cuisine: 'Malay', rating: 4.4,
            aiInsight: 'This open-air satay corridor is the last surviving street-food tradition in Singapore\'s CBD — every other hawker scene in the district has been moved indoors.',
            address: '18 Raffles Quay, Singapore 048582',
            duration: '1 hour',
            proTip: 'Stall 7 & 8 have the best mutton satay — slightly charred edges with tender center. Order at least 20 sticks.',
            travelFromPrevious: { mode: 'walk', duration: '15 mins', distance: '1.2 km' },
          },
          {
            title: 'Supertree Grove Light Show',
            description: 'Lie on the grass beneath the 50m-tall Supertrees as they come alive with the "Garden Rhapsody" light-and-music show — a synchronized display of 162,900 lights set to orchestral music. Free.',
            image: null, lat: 1.2816, lng: 103.8636,
            timeOfDay: 'Evening', category: 'LANDMARK', mealType: 'NONE', rating: 4.9,
            aiInsight: 'The Supertrees aren\'t just decorative — they\'re vertical gardens housing over 162,900 plants AND they function as environmental engines, collecting rainwater, venting air, and generating solar energy.',
            address: '18 Marina Gardens Dr, Singapore 018953',
            duration: '30 mins',
            proTip: 'The 7:45 PM show is less crowded than the 8:45 PM show. Bring a mat and lie flat for the full canopy effect.',
            travelFromPrevious: { mode: 'walk', duration: '18 mins', distance: '1.5 km' },
          },
        ],
      },
    ],
  },
};
