export const switzerlandData = {
  slug: 'switzerland',
  destination: 'Switzerland',
  heroImage: 'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?q=80&w=2000&auto=format&fit=crop',
  itinerary: {
    destination: 'Switzerland',
    heroImage: 'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?q=80&w=2000&auto=format&fit=crop',
    estimatedTotalExpense: '$150–$250',
    estimatedCostINR: { min: 12500, max: 21000 },
    placesCount: 5,
    totalDistanceKm: 12,
    difficulty: 'Moderate',
    bestTimeToVisit: 'June to September (hiking), December to March (skiing)',
    localCurrency: 'Swiss Franc (CHF 1 ≈ $1.12)',
    language: 'German, French, Italian, Romansh',
    travelTips: [
      'Buy a Swiss Travel Pass for unlimited trains, buses, and boats — it pays for itself in a single day',
      'Tap water is pristine everywhere — fill your bottle at any public fountain',
      'Restaurants add service charges; tipping is optional (round up if pleased)',
      'Shops close early on Saturdays and all day Sundays outside tourist zones',
      'Mountain weather changes in minutes — always carry a rain layer even on sunny days',
    ],
    suggestedStays: [
      { name: 'Hotel & Hostel Nyon', type: 'Hostel', priceRange: 'CHF 45–80', neighborhood: 'Interlaken Ost' },
      { name: 'Hotel Interlaken', type: 'Hotel', priceRange: 'CHF 150–220', neighborhood: 'Interlaken Center' },
      { name: 'Victoria-Jungfrau Grand Hotel', type: 'Hotel', priceRange: 'CHF 400–600', neighborhood: 'Höheweg, Interlaken' },
    ],
    days: [
      {
        day: 1,
        title: 'Peaks, Lakes & Fondue',
        summary: 'Ride the cogwheel railway to Harder Kulm for a jaw-dropping panorama, cruise turquoise Lake Brienz, wander Interlaken\'s old town, and end with cheese fondue by candlelight.',
        estimatedCost: '$130–$220',
        activities: [
          {
            title: 'Harder Kulm Panorama',
            description: 'Take the century-old funicular up 1,322m to Harder Kulm\'s Two Lakes Bridge — a glass-floored viewing platform suspended over the cliff edge with Eiger, Mönch, and Jungfrau filling the horizon.',
            image: null, lat: 46.6950, lng: 7.8600,
            timeOfDay: 'Morning', category: 'LANDMARK', mealType: 'NONE', rating: 4.8,
            aiInsight: 'The viewing platform hangs directly between Lake Thun and Lake Brienz — it\'s the only place on Earth where you can see two major Alpine lakes simultaneously from a single vantage point.',
            address: 'Harder Kulm, 3800 Interlaken, Switzerland',
            duration: '2 hours',
            proTip: 'Take the first funicular at 9:10 AM — you\'ll have the platform nearly to yourself.',
            travelFromPrevious: null,
          },
          {
            title: 'Restaurant Bären',
            description: 'A cozy Bernese inn serving rösti (crispy potato cake) topped with raclette cheese, paired with local Rugenbräu beer. Traditional, unfussy Swiss comfort food.',
            image: null, lat: 46.6863, lng: 7.8632,
            timeOfDay: 'Lunchtime', category: 'RESTAURANT', mealType: 'LUNCH', cuisine: 'Swiss', rating: 4.5,
            aiInsight: 'Bären has been feeding travelers since the 1600s — the rösti recipe hasn\'t changed in four generations.',
            address: 'Hauptstrasse 20, 3800 Matten bei Interlaken',
            duration: '1 hour',
            proTip: 'Order the Berner Platte if you\'re hungry — a massive meat-and-sausage board with sauerkraut.',
            travelFromPrevious: { mode: 'train', duration: '12 mins', distance: '1.5 km' },
          },
          {
            title: 'Lake Brienz Cruise',
            description: 'Glide across Lake Brienz\'s impossibly turquoise water on a Belle Époque paddle steamer. Pass the Giessbach Falls — a 500m cascade dropping directly into the lake from forested cliffs.',
            image: null, lat: 46.7200, lng: 7.9700,
            timeOfDay: 'Afternoon', category: 'ACTIVITY', mealType: 'NONE', rating: 4.7,
            aiInsight: 'Lake Brienz is fed by glacial melt, which gives it that unreal turquoise color — it\'s actually bluer than Lake Thun because it\'s colder and has finer rock flour suspended in it.',
            address: 'BLS Schifffahrt, Interlaken Ost Pier, Switzerland',
            duration: '2 hours',
            proTip: 'Sit on the right side (starboard) heading east for the best Giessbach Falls view.',
            travelFromPrevious: { mode: 'walk', duration: '15 mins', distance: '1 km' },
          },
          {
            title: 'Interlaken Old Town Stroll',
            description: 'Walk the Höheweg promenade with the Jungfrau massif as your backdrop. Browse the Swiss watch shops, duck into the charming Unterseen quarter with its 13th-century church.',
            image: null, lat: 46.6866, lng: 7.8528,
            timeOfDay: 'Afternoon', category: 'LANDMARK', mealType: 'NONE', rating: 4.4,
            aiInsight: 'The Höhematte — the wide green park along Höheweg — is protected by law from development, ensuring the Jungfrau view is never blocked. Paragliders land here daily.',
            address: 'Höheweg, 3800 Interlaken, Switzerland',
            duration: '1 hour',
            proTip: 'Cross the bridge to Unterseen village for fewer tourists and better photos of medieval timber houses.',
            travelFromPrevious: { mode: 'bus', duration: '20 mins', distance: '4 km' },
          },
          {
            title: 'Fondue at Restaurant Laterne',
            description: 'End the day with a bubbling caquelon of moitié-moitié fondue (Gruyère & Vacherin) in a candlelit 17th-century timber house. Pair with crisp Fendant white wine.',
            image: null, lat: 46.6870, lng: 7.8490,
            timeOfDay: 'Evening', category: 'RESTAURANT', mealType: 'DINNER', cuisine: 'Swiss', rating: 4.6,
            aiInsight: 'Laterne uses direct-from-farm Gruyère aged 14 months — most tourist restaurants use industrial cheese. The difference is night and day.',
            address: 'Obere Gasse 18, 3800 Unterseen, Switzerland',
            duration: '1.5 hours',
            proTip: 'Save room for the meringue with double cream — it\'s a Bernese Oberland specialty you won\'t find outside Switzerland.',
            travelFromPrevious: { mode: 'walk', duration: '8 mins', distance: '0.5 km' },
          },
        ],
      },
    ],
  },
};
